---
- name: Debian - Ensure trusty dependencies are installed
  block:
    - name: Debian - Ensure trusty python dependencies are installed
      apt:
        name:
          - python-urllib3
          - python-openssl
          - python-pyasn1
          - python-pip
        state: present

    - name: Debian - Ensure ndg-httpsclient pip is installed
      pip:
        name: ndg-httpsclient
        state: present
  when:
    - use_repository | bool
    - ansible_distribution_release == "trusty"

- name: Debian - Ensure beats apt repository is configured
  block:
    - name: Debian - Ensure apt-transport-https is installed
      apt:
        name: apt-transport-https
        state: present
        cache_valid_time: 86400
      notify: "restart {{ beat }}"

    - name: Debian - Add beats repository key
      apt_key:
        url: "{{ repo_key }}"
        state: present

    - name: Debian - Add beats repository
      apt_repository:
        repo: "deb {{ repo_url }} stable main"
        state: present
  when: use_repository | bool

- name: "Debian - unhold {{ beat }} version for install"
  command: "apt-mark unhold {{ beat }}"
  changed_when: False

- name: "Debian - Ensure {{ beat }} is installed"
  apt:
    name: "{{ beat }}{{ beats_version | d(False) | ternary('=' + beats_version |d(''), '') }}"
    state: present
    dpkg_options: 'force-downgrade,force-confold,force-confdef'
    force: yes
    cache_valid_time: 86400
  when: use_repository | bool
  notify: "restart {{ beat }}"

- name: "Debian - hold {{ beat }} version"
  command: "apt-mark hold {{ beat }}"
  when: version_lock | bool
  changed_when: False

- name: "Debian - Ensure {{ beat }} is installed from url"
  block:
    - name: Set os_arch fact
      set_fact:
        os_arch: "{{ ansible_architecture == 'x86_64' | ternary('amd64', 'i386') }}"

    - name: "Debian - Download {{ beat }} from url"
      get_url:
        url: "{{ custom_package_url | default('{{ beats_package_url }}/{{ beat }}/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb', true) }}"
        dest: "/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb"
        validate_certs: no

    - name: "Debian - Ensure {{ beat }} is installed from downloaded package"
      apt:
        deb: "/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb"
      notify: "restart {{ beat }}"
  when: not ( use_repository | bool )
