---
- name: Ensure libselinux-python on CentOS 6.x
  yum:
    name: libselinux-python
    state: present
    update_cache: yes
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: Redhat - add beats repository
  template:
    src: beats.repo.j2
    dest: /etc/yum.repos.d/beats.repo
  when: use_repository | bool

- name: RedHat - install yum-version-lock
  yum:
    name: yum-plugin-versionlock
    state: present
    update_cache: yes

- name: "RedHat - unlock {{ beat }} for install"
  shell: "yum versionlock delete {{ beat }} || true"  # noqa 303
  changed_when: False

- name: "RedHat - Ensure {{ beat }} is installed"
  yum:
    name: "{{ beat }}{{ beats_version | bool | ternary('-{{ beats_version }}', '') }}"
    state: present
    update_cache: yes
  when: use_repository | bool
  notify: "restart {{ beat }}"

- name: "RedHat - lock {{ beat }} version"
  shell: "yum versionlock add {{ beat }}{{ beats_version | bool | ternary('={{ beats_version }}', '') }}"  # noqa 303
  when: version_lock | bool
  changed_when: False

- name: "RedHat - Install {{ beat }} from url"
  yum:
    name: "{{ custom_package_url | default('{{ beats_package_url }}/{{ beat }}-{{ beats_version }}-{{ ansible_architecture }}.rpm', true) }}"
    state: present
  when: not ( use_repository | bool )
  notify: "restart {{ beat }}"
